# Generated by Django 2.2.2 on 2019-06-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=400, null=True, verbose_name='Company Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_pin', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=400, null=True, verbose_name='Last Name')),
                ('email', models.CharField(max_length=400, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=400, null=True, verbose_name='Password')),
                ('user_rights', models.CharField(choices=[('standard', 'Standard'), ('administrator', 'Administrator'), ('company_administrator', 'Company Administrator')], max_length=256, verbose_name='User Rights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Company', verbose_name='Company')),
            ],
        ),
    ]
