# Generated by Django 2.1.15 on 2020-01-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.BooleanField()),
                ('product', models.BooleanField()),
                ('size', models.BooleanField()),
                ('speed', models.BooleanField()),
                ('ports', models.BooleanField()),
                ('poe', models.BooleanField()),
                ('rack_units', models.BooleanField()),
                ('status', models.BooleanField()),
                ('checkout', models.BooleanField()),
                ('location', models.BooleanField()),
                ('serial_number', models.BooleanField()),
                ('created_at', models.BooleanField()),
                ('updated_at', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=400, null=True, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=400, null=True, verbose_name='Model')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='userdepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userdepartment', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Company', verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='usersub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('studentid', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userdepartment', verbose_name='department')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.Company', verbose_name='company')),
            ],
        ),
    ]
