# Generated by Django 2.2.2 on 2019-06-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoints',
            name='active',
        ),
        migrations.RemoveField(
            model_name='asas',
            name='active',
        ),
        migrations.RemoveField(
            model_name='desktops',
            name='active',
        ),
        migrations.RemoveField(
            model_name='junipers',
            name='active',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='active',
        ),
        migrations.RemoveField(
            model_name='paloaltos',
            name='active',
        ),
        migrations.RemoveField(
            model_name='routers',
            name='active',
        ),
        migrations.RemoveField(
            model_name='servers',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='active',
        ),
        migrations.RemoveField(
            model_name='switches',
            name='active',
        ),
        migrations.RemoveField(
            model_name='wirelessadapters',
            name='active',
        ),
    ]
