# Generated by Django 2.2.2 on 2019-06-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190619_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='studentid',
            field=models.CharField(default='123456789', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='period',
            field=models.CharField(choices=[('1-2', 'Period 1/2'), ('3-4', 'Period 3/4'), ('4-5', 'Period 4/5'), ('5-6', 'Period 5/6')], max_length=256, verbose_name='Period'),
        ),
    ]
