# Generated by Django 2.1.15 on 2020-01-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
